# Generated by Django 5.2.12 on 2026-04-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='file_count',
            field=models.IntegerField(default=0, help_text='Number of DICOM slices uploaded'),
        ),
        migrations.AddField(
            model_name='visit',
            name='mri_folder',
            field=models.CharField(blank=True, help_text='Relative path to saved DICOM folder (e.g. mri_scans/visit_12/)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='mri_format',
            field=models.CharField(choices=[('dicom', 'DICOM Series'), ('nifti', 'NIfTI (.nii / .nii.gz)'), ('zip', 'ZIP Archive'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='mri_file',
            field=models.FileField(blank=True, null=True, upload_to='mri_scans/'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente...'), ('processing', 'En cours...'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=20),
        ),
    ]
