# Generated by Django 5.2.12 on 2026-04-05 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biomarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(help_text='Hippocampal volume in mm3')),
                ('surface', models.FloatField(help_text='Hippocampal surface area')),
                ('asymmetry', models.FloatField(help_text='Left/Right asymmetry index')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biomarker', to='visits.visit')),
            ],
        ),
    ]
