# Generated by Django 5.2.12 on 2026-04-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='kendall_distance',
            field=models.FloatField(blank=True, help_text='Deformation distance in Kendall shape space (Approach 2)', null=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='predicted_volume_1y',
            field=models.FloatField(blank=True, help_text='Predicted volume in 1 year estimated by Approach 1 (LSTM)', null=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='risk_score',
            field=models.FloatField(blank=True, help_text='Risk score generated by Approach 3 (Random Forest)', null=True),
        ),
    ]
