from django.db import models
from visits.models import Visit

class Biomarker(models.Model):
    visit = models.OneToOneField(Visit, on_delete=models.CASCADE, related_name='biomarker')
    volume = models.FloatField(help_text="Hippocampal volume in mm3")
    surface = models.FloatField(help_text="Hippocampal surface area")
    asymmetry = models.FloatField(help_text="Left/Right asymmetry index")
    
    # Nouvelles métriques pour les approches AI
    risk_score = models.FloatField(null=True, blank=True, help_text="Risk score generated by Approach 3 (Random Forest)")
    kendall_distance = models.FloatField(null=True, blank=True, help_text="Deformation distance in Kendall shape space (Approach 2)")
    predicted_volume_1y = models.FloatField(null=True, blank=True, help_text="Predicted volume in 1 year estimated by Approach 1 (LSTM)")

    def __str__(self):
        return f"Biomarkers for {self.visit}"
